# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  ignore:
      - dependency-name: none

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  ignore:
    - dependency-name: bootstrap
    - dependency-name: webpack
    - dependency-name: webpack-cli
    - dependency-name: copy-webpack-plugin
    - dependency-name: expose-loader
    - dependency-name: terser-webpack-plugin
    - dependency-name: html-webpack-plugin

- package-ecosystem: npm
  directory: "/buildtools/copyright"
  schedule:
    interval: daily
    time: "02:00"
  ignore:
      - dependency-name: none
