# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json

version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  ignore:
      - dependency-name: none

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  ignore:
      - dependency-name: none

- package-ecosystem: npm
  directory: "/buildtools/copyright"
  schedule:
    interval: daily
    time: "02:00"
  ignore:
      - dependency-name: none
