extends:
  - openlayers
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
env:
  jquery: true
parserOptions:
  ecmaVersion: 2017
  project: ./tsconfig-eslint.json
plugins:
  - copyright
  - '@typescript-eslint'
rules:
  no-console: 0
  import/no-unresolved: 0
  import/extensions: 0
  no-unused-vars: error
  prettier/prettier: 0
  sort-imports-es6-autofix/sort-imports-es6: 0
  jsdoc/require-param-description: 0
  jsdoc/require-property-description: 0
  jsdoc/require-returns-description: 0
  jsdoc/require-param-type: 0
  jsdoc/require-returns-type: 0
  jsdoc/check-types: 0
  jsdoc/check-tag-names: 0
  copyright/copyright: error
  '@typescript-eslint/indent': 0
  '@typescript-eslint/no-unused-vars': 0
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/camelcase': 0
  '@typescript-eslint/no-unnecessary-type-assertion':
    - error
  '@typescript-eslint/no-for-in-array':
    - error
  '@typescript-eslint/no-this-alias':
    - error
  '@typescript-eslint/no-useless-constructor':
    - error
  '@typescript-eslint/prefer-for-of':
    - error
  '@typescript-eslint/prefer-includes':
    - error
  '@typescript-eslint/prefer-string-starts-ends-with':
    - error
  '@typescript-eslint/restrict-plus-operands':
    - error
  '@typescript-eslint/ban-ts-ignore': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/no-var-requires': 0
  '@typescript-eslint/no-empty-function': 0
  '@typescript-eslint/ban-ts-comment': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-explicit-any': 0

settings:
  jsdoc:
    preferredTypes:
      '[]':
      'Array<>': '[]'
