extends:
  - ./.eslintrc.yaml

rules:
  no-prototype-builtins: error
  no-case-declarations: error
  jsdoc/check-tag-names: error
  jsdoc/check-types: error
  jsdoc/no-undefined-types: error
  jsdoc/require-returns-description: error
  jsdoc/require-param-description: error
  jsdoc/require-property-description: error
  '@typescript-eslint/explicit-module-boundary-types': error
  '@typescript-eslint/no-unsafe-member-access': error
  '@typescript-eslint/no-unsafe-assignment': error
  '@typescript-eslint/no-unsafe-return': error
  '@typescript-eslint/no-unsafe-call': error
  '@typescript-eslint/no-floating-promises': error
  '@typescript-eslint/unbound-method': error
  '@typescript-eslint/restrict-template-expressions': error
  '@typescript-eslint/no-misused-promises': error
  '@typescript-eslint/require-await': error
