language: python
sudo: false
branches:
  only:
  - master
script:
- make check
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git diff --check ${TRAVIS_BRANCH} -- ; fi
after_success:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make gh-pages-from-travis || /bin/true'
env:
  global:
  - secure: "WZWqYrRy5uhk3IgXT9HXAL1zrZfrmJbbglF4gwNpSnrZkLv63gFwpMj6bjxOPKPouU76p4K7x/fnZb/FWRl6/fEnJzLKNvbknQtvmC4dAoHLynFVpilYholmdscT2fo/SOmE3XKOA4EJTF7oxToCgT2+e68e/oH87izXUn4FvK8="
cache:
  apt: true
  directories:
  - node_modules

