sudo: false

language: node_js

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python-virtualenv

node_js:
- "4"
- "0.10"

cache:
  apt: true
  directories:
  - node_modules

before_script:
- npm prune

script:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git diff --check ${TRAVIS_BRANCH} -- ; fi
- if [ "`git grep @fileoverview src contribs`" != "" ] ; then echo "Using @fileoverview breaks the documentation main page" ; false ; fi
- if [ "`git grep @example src contribs`" != "" ] ; then echo "We don't use @example to have the example in the description" ; false ; fi
- make check
- make .build/examples-hosted/index.html
- make .build/examples-hosted/contribs/gmf/index.html
- make apidoc

after_success:
- openssl aes-256-cbc -K $encrypted_66d875d20fac_key -iv $encrypted_66d875d20fac_iv -in deploy_key.enc -out ~/.ssh/id_rsa -d | true
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "Travis"
- git config --global user.email "travis@travis-ci.org"
- export GIT_BRANCH=${TRAVIS_BRANCH}
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && make gh-pages'
- openssl aes-256-cbc -K $encrypted_66d875d20fac_key -iv $encrypted_66d875d20fac_iv -in .transifexrc.enc -out $HOME/.transifexrc -d
- '[ "${TRAVIS_BRANCH}" = "master" ] && make transifex-send'
- 'cat .build/coverage/lcov.info | node ./node_modules/coveralls/bin/coveralls.js'
