---
version: 1
update_configs:
  - package_manager: javascript
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          update_type: all

  - package_manager: python
    directory: /
    update_schedule: live
    automerged_updates:
      - match:
          update_type: all
    allowed_updates:
      - match:
          dependency_type: indirect
    ignored_updates:
      - match:
          dependency_name: none
