checks:
  black: False
  isort: False
  codespell: False
  required_workflows: False
  versions:
    rebuild: False

audit:
  npm:
    cwe_ignore:
      - CWE-400 # Uncontrolled Resource Consumption
      - CWE-22 # Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
