checks:
  required_workflows:
    main.yaml: False
    rebuild.yaml: False
  versions:
    rebuild: False
  codespell:
    ignore_re:
      - ^contribs/gmf/test/spec/data/themescapabilities\.js$
      - ^contribs/gmf/test/spec/data/themes\.js$
      - ^buildtools/asitvd.capabilities\.xml$
      - ^examples/measure\.js$

audit:
  npm:
    cwe_ignore:
      - CWE-400 # Uncontrolled Resource Consumption
      - CWE-22 # Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
