{
  plugins: [
    'googshift',
  ],
  rules: {
    'googshift/no-duplicate-requires': 'error',

    # FIXME launch 'error' again when 'ngeo.module' will be able to be an exception
    'googshift/no-missing-requires': ['warn', {
      prefixes: ['ngeo', 'ol']
    }],

    'googshift/no-unused-requires': 'warn',

    'googshift/one-provide-or-module': ['error', {
      entryPoints: ['ngeo'],
      root: 'src'
    }],

    'googshift/requires-first': 'error',

    'googshift/valid-provide-and-module': ['error', {
      entryPoints: ['ngeo'],
      root: 'src/module',
      replace: '..|ngeo'
    }],

    'googshift/valid-requires': 'error',
  }
}
