---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Audit
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '2.4'
          - '2.5'

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ matrix.branch }}
      - run: sudo npm install --global better-npm-audit npm
      - run: npm install --package-lock
      - run: |
          node /usr/local/lib/node_modules/better-npm-audit audit --level moderate \
          --ignore=$(cat npm-cve-ignore 2> /dev/null || true) || (
            npm audit fix --force
            git diff
            git diff-index --quiet HEAD
          )
