---
name: Audit

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  audit:
    runs-on: ubuntu-20.04
    name: Audit
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '2.4'
          - '2.5'
          - master

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - run: sudo python3 -m pip install --requirement=ci/requirements.txt

      - name: Audit
        run: c2cciutils-audit
