---

name: Audit

on:
  schedule:
    - cron: "30 2 * * *"

jobs:
  main:
    runs-on: ubuntu-18.04
    name: Audit
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '2.4'
          - '2.5'

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ matrix.branch }}
      - run: npm install --package-lock
      - run: npm audit fix --force
      - run: git diff
      - run: git diff-index --quiet HEAD
