---

name: Clean docker hub tags

on:
  delete

jobs:
  clean:
    runs-on: ubuntu-18.04
    name: Clean docker hub tags
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v1
        with:
          ref: gh-pages
      - name: Clean ghpages
        run: |
          git config --global user.name "Continuous integration"
          git config --global user.email "ci@comptocamp.org"
          git rm -r $(cat ${GITHUB_EVENT_PATH}|jq --raw-output .ref)
          git commit --amend
          remote_repo="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/camptocamp/ngeo.git"
          git push "${remote_repo}" gh-pages --force
