---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 30
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    env:
      MAIN_BRANCH: master
      CI: true
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin

    steps:
      - run: /opt/google/chrome/chrome --version

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: actions/checkout@v2

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: pypi docker
        if: github.repository == 'camptocamp/ngeo'

      - run: sudo python3 -m pip install --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: |
          sudo rm /etc/apt/sources.list.d/*.list
          sudo apt update
          sudo apt install g++-10 libgbm1 graphicsmagick fonts-liberation2

      - run: buildtools/set-version
      - run: make .build/node_modules.timestamp

      # Lint
      - run: npx tsc --version
      - run: npm run typecheck
      - run: make lint
      - run: make test
      - run: make check-examples-checker
      # Webpack build of ngeo/gmf examples and gmf apps
      - run: NODE_ENV=production make examples-hosted
      - run: make check-examples
      - uses: actions/upload-artifact@v1
        with:
          name: Examples hosted
          path: .build/examples-hosted
        if: failure()

      # Generate API doc
      - run: npm run doc
      - run: make jsdoc
      - run: npm run build-api
      - uses: actions/upload-artifact@v1
        with:
          name: Npm logs
          path: /home/runner/.npm/_logs
        if: failure()

      - run: echo "//registry.npmjs.org/:_authToken=$(gopass gs/ci/npm/token)" > ~/.npmrc
        if: github.repository == 'camptocamp/ngeo'
      - name: Build ~/.transifexrc
        run: |
          summon --yaml '
            USERNAME: !var gs/ci/transifex/rw/username
            PASSWORD: !var gs/ci/transifex/rw/password
          ' bash -c 'envsubst < buildtools/transifexrc.tmpl > ~/.transifexrc'
        if: github.repository == 'camptocamp/ngeo'

      - run: make transifex-send
        if: github.repository == 'camptocamp/ngeo' && github.ref == format('refs/heads/{0}', env.MAIN_BRANCH)
      - run: buildtools/publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.repository == 'camptocamp/ngeo'
      - run: buildtools/npm-publish
        if: github.repository == 'camptocamp/ngeo'

      - name: Notify c2cgeoportal
        run: >
          curl --request POST --header "Content-Type: application/json"
          --header 'Accept: application/vnd.github.v3+json'
          --header "Authorization: token ${{ secrets.GOPASS_CI_GITHUB_TOKEN }}"
          https://api.github.com/repos/camptocamp/c2cgeoportal/dispatches
          --data '{"event_type": "geomapfish_${{ env.MAIN_BRANCH }}_updated"}'
        if: >
          github.ref == format('refs/heads/{0}', env.MAIN_BRANCH)
          && github.repository == 'camptocamp/ngeo'
